<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="10.693" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2024-12-19T11:44:28" tests="0" file="cypress/e2e/api/fakestore_spec.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Fake Store API" timestamp="2024-12-19T11:44:28" tests="3" time="10.690" failures="1">
    <testcase name="Fake Store API Successfully GETs products" time="0.903" classname="Successfully GETs products">
    </testcase>
    <testcase name="Fake Store API Successfully GET Product by Id" time="0.364" classname="Successfully GET Product by Id">
    </testcase>
    <testcase name="Fake Store API Successfully POST Product by Id" time="0.000" classname="Successfully POST Product by Id">
      <failure message="expected { Object (id, title, ...) } to have property &apos;id&apos; of undefined, but got 21" type="AssertionError"><![CDATA[AssertionError: expected { Object (id, title, ...) } to have property 'id' of undefined, but got 21
    at Context.eval (webpack://clear/./cypress/e2e/api/fakestore_spec.cy.js:36:40)]]></failure>
    </testcase>
  </testsuite>
</testsuites>